Week7/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.user_stuff.urls', namespace="user", app_name="user_stuff")),
    url(r'^movies/', include('apps.movies.urls', namespace="movies", app_name="movies"))
]

apps/movies/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^actor/create', views.create_actor, name='create_actor'),
    url(r'^movie/create', views.create_movie, name='create_movie'),
    url(r'^actor/(?P<id>\d+)', views.show_actor, name='actor'),
    url(r'^movie/(?P<id>\d+)/$', views.show_movie, name='movie'),
    # url(r'^movie/append_cast/(?P<id>\d+)/$', views.append_cast, name='append_cast'),
]

apps/user_stuff/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'user/create', views.create, name='create')
]

apps/game_stuff/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/movies/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Actor(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

class Movie(models.Model):
    title = models.CharField(max_length=100)

    # this_movie.cast.add(some_actor)
    # this_movie.cast.remove(some_actor)

class Cast(models.Model):
    film = models.ForeignKey(Movie)
    actor = models.ForeignKey(Actor)
    role = models.CharField(max_length=100)

apps/user_stuff/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import bcrypt
from django.db import models

class TheUserManager(models.Manager):
    def create_or_fail(self, client):
        errors = []
        is_valid = True
        # first_name, last_name
        if len(client['first_name']) < 4 or len(client['last_name']) < 4:
            errors.append("name values must be at least three characters")
            is_valid = False
        
        # username
        if len(self.filter(username=client['username'])) > 0:
            print 'user here'
            errors.append("username exists in system")
            is_valid = False
            
        # password
        if len(client['password']) < 9:
            errors.append("passwords must be at least 8 characters")
            
        # password confirm
        if client['password'] != client['password_confirm']:
            errors.append("passwords do not match")

        if is_valid:
            salt = bcrypt.gensalt()
            hashed_pw = bcrypt.hashpw(client['password'].encode(), salt)
            print salt
            print hashed_pw
            return { "is_valid" : is_valid, "obj": self.create(
                first_name = client['first_name'],
                last_name = client['last_name'],
                username = client['username'],
                password = client['password'],
                salt = salt
            )}
        return {'is_valid' : is_valid, 'obj' : errors}

# Create your models here.
class TheUser(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=255)
    salt = models.CharField(max_length=255)
    objects = TheUserManager()

    def __str__(self):
        return self.first_name + " " + self.last_name

apps/game_stuff/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

apps/movies/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import Actor, Movie, Cast
from django.shortcuts import render, redirect

# Create your views here.
def index(req):
    print 'in index movies'
    context = {
        'actors': Actor.objects.all(),
        'movies': Movie.objects.all()
    }
    return render(req, "movies/index.html", context)

def create_actor(req):
    print 'in create actor'
    Actor.objects.create(
        first_name=req.POST['first_name'],
        last_name=req.POST['last_name']
    )
    return redirect("movies:index")

def create_movie(req):
    print 'in create movie'
    Movie.objects.create(title=req.POST['title'])
    return redirect('movies:index')

def show_actor(req, id):
    this_actor = Actor.objects.get(id=id)
    context = {
        "actor": this_actor,
    }
    print this_actor
    return render(req, "movies/actor.html", context)

def show_movie(req, id):
    this_movie = Movie.objects.get(id=id)
    
    context = {
        "movie": this_movie,
        "actors": Actor.objects.all()
    }
    print this_movie
    return render(req, "movies/movie.html", context)

    return redirect("movies:index")

apps/user_stuff/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import TheUser
from django.shortcuts import render, redirect
from django.contrib import messages

TEMPLATE_NAMES = {
    'index': 'user_stuff/index.html'
}

# Create your views here.
def index(req):
    return redirect("movies:index")
    # print TheUser.objects.all()
    # return render(req, TEMPLATE_NAMES['index'])

def create(req):
    print 'in user create'
    if (req.POST):
        user_or_errors = TheUser.objects.create_or_fail(req.POST)
        if not user_or_errors['is_valid']:
            for error in user_or_errors['obj']:
                messages.error(req, error)
            return render(req, TEMPLATE_NAMES['index'])
    return redirect('user:index')

apps/movies/templates/movies/actor.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <h1>Actor Details</h1>
        <h3>First Name: {{actor.first_name}}</h3>
        <h3>Last Name: {{actor.last_name}}</h3>
        <!--<h3>Filmography</h3>
        <ul>
            {% for movie in films %}
                <li>{{movie.film.title}} as {{movie.role}}</li>
            {% endfor %}
        </ul>-->
    </body>
</html>

apps/movies/templates/movies/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <h2>Add Actor</h2>
        <form action='{% url "movies:create_actor" %}' method="POST">{% csrf_token %}
            <div class='form-group'>
                <label for="first_name">First Name</label>
                <input type="text" name="first_name">
            </div>
            <div class='form-group'>
                <label for="last_name">Last Name</label>
                <input type="text" name="last_name">
            </div>
            <input type="submit" value='Add'>
        </form>

        <h2>Add Movie</h2>
        <form action='{% url "movies:create_movie" %}' method="POST">{% csrf_token %}
            <div class='form-group'>
                <label for="title">Title</label>
                <input type="text" name="title">
            </div>
            <input type="submit" value='Add'>
        </form>
         <hr>
            <h3>Actors</h3>
            <ul>
                {% for actor in actors %}
                <li><a href="{% url 'movies:actor' actor.id %}">{{actor.first_name}} {{actor.last_name}}</a></li>
                {% endfor %}
            </ul>
             <h3>Movies</h3>
            <ul>
                {% for movie in movies %}
                <li><a href="{% url 'movies:movie' movie.id %}">{{movie.title}}</a></li>
                {% endfor %}
            </ul>
    </body>
</html>

apps/movies/templates/movies/movie.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <h1>Movie Details</h1>
        <h2>Title: {{movie.title}}</h2>
        <hr>
        <!--<form action='{% url "movies:append_cast" movie.id %}' method="POST">{% csrf_token %}
            <select name='actor_in_cast'>
                {% for actor in actors %}
                <option value="{{actor.id}}">{{ actor.first_name }} {{ actor.last_name }}</option>
                {% endfor %}
            </select>
            Role: <input type="text" name="role">
            <input type="submit" value="Add To Cast">
        </form>-->
    </body>
</html>

apps/user_stuff/templates/user_stuff/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>
        <h1>Welcome to my SITE</h1>
        <hr>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        <hr>
        {% endif %}
        <h2>Register</h2>
        <form action='{% url "user:create" %}' method='post'> {% csrf_token %}
            <div class='form-group'>
                <label for="first_name">First Name</label>
                <input type="text" name="first_name">
            </div>
            <div class='form-group'>
                <label for="last_name">Last Name</label>
                <input type="text" name="last_name">
            </div>
            <div class='form-group'>
                <label for="username">Username</label>
                <input type="text" name="username">
            </div>
            <div class='form-group'>
                <label for="password">Password</label>
                <input type="password" name="password">
            </div>
            <div class='form-group'>
                <label for="password_confirm">Confirm Password</label>
                <input type="password_confirm" name="password_confirm">
            </div>
            <input type="submit" value="Register">
           
        </form>
    </body>
</html>